### ISSUE TITLE
Invalid data found when processing input

### ISSUE THREAD

**Issue by ptrstn** [Philippus229/DLNOW#1]
Hi!
First of all, thanks alot for this great tool! 

I was able to get it to run and download and merge the video/audio segments of an episode, but the ```ffmpeg``` copy step in the ```merge_clean``` function doesn't seem to work. 
Could it be because the content is DRM encrypted?

I get the following error message:

```bash
$ python DLNOW.py 
```

```
[...]
0: dash
1: dashhd (audio issues)
Dash type > 0
Quality options not implemented yet, defaulting to highest...
Downloading video segment 1 of 1783...
Downloading video segment 2 of 1783...
Downloading video segment 3 of 1783...
[...]
Downloading video segment 1783 of 1783...
Quality options not implemented yet, defaulting to highest...
Downloading audio segment 1 of 1783...
[...]
Downloading audio segment 1783 of 1783...
Merging audio segments...
Merging video segments...
Merging audio and video...
ffmpeg version n4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.3.0 (Arch Linux 9.3.0-1)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55dd339b32c0] could not find corresponding track id 1
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55dd339b32c0] could not find corresponding trex (id 1)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55dd339b32c0] could not find corresponding track id 0
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55dd339b32c0] trun track id unknown, no tfhd was found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55dd339b32c0] error reading header
video.m4v: Invalid data found when processing input
Done!
```

Running the ```ffmpeg``` command manually also retuns the same error message:

```bash
$ ffmpeg -i video.m4v -i audio.m4a -c:v copy -c:a copy test.mp4
```

```
 ffmpeg -i video.m4v -i audio.m4a -c:v copy -c:a copy test.mp4
ffmpeg version n4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.3.0 (Arch Linux 9.3.0-1)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x561ca14db2c0] could not find corresponding track id 1
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x561ca14db2c0] could not find corresponding trex (id 1)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x561ca14db2c0] could not find corresponding track id 0
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x561ca14db2c0] trun track id unknown, no tfhd was found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x561ca14db2c0] error reading header
video.m4v: Invalid data found when processing input
```

Do you know what I could do to make it work?
Thanks!

**Comment by Philippus229** [comment]
Hi!
First up, thank you for using my downloader!
I actually only wrote it to download some anime and never thought anyone
except me was actually going to use it. Because of that I also never tested
it with any other shows, which explains how this could've happened.
There are many possible explanations for why it might have failed. For
example, the MPD parsing is complete trash, but that doesn't seem to be the
problem in your case since it was able to download the segments.
Neither do I think DRM encryption could have caused this since it shouldn't
even be able to download encrypted content.
Would you mind telling me what exactly you were trying to download?
Because at the moment I have no clue as to what might have gone wrong.

PS:
It might take a while for me to respond since it's already 2:29am and I
don't plan on staying up much longer.
Also, I don't know when I'll get around to fixing it since I've still got
quite a bit of homework to do.

PPS:
Kurze Frage: Wäre Ihnen Englisch oder Deutsch lieber? Mir ist es nämlich
ziemlich egal.
Ich bin übrigens auch aus Rheinland-Pfalz (gehe zur Zeit auf's
Reichswald-Gymnasium in Ramstein-Miesenbach (bzw. momentan ja nicht)).

Am Di., 28. Apr. 2020 um 23:48 Uhr schrieb Peter Stein <
notifications@github.com>:

**Comment by ptrstn** [comment]
Ich habs mit zwei Sendungen probiert, beide hatten das gleiche Ergebnis. 

Einmal war es die letzte Folge von "Das perfekte Dinner", und dann hab ich random eine ausgewählt (ich glaub ich hab die letzte Show in der Liste genommen, also "Überlebenstraining - Ein Muss oder Panikmache?")

Für welchen Anime hat's denn geklappt? Ich kann es damit dann noch einmal versuchen

**Comment by Philippus229** [comment]
Das ist wirklich ein krasser Zufall. Ich geh sogar öfter mal in Landstuhl
einkaufen (meistens im Kaufland oder Toom).

Ich hab's mir mal angeschaut.

Es liegt wohl doch an der DRM-Verschlüsselung.

Hatte komplett vergessen, dass ich in der Version auf GitHub das
Herunterladen von DRM-geschützten Inhalten unnötiger Weise erlaubt hatte.
Ich sollte vielleicht mal eine Warnung einbauen, dass es nicht
funktioniert, oder die Option zum Download solcher Inhalte einfach komplett
entfernen.
Hab zwar vor einiger Zeit mal mit DRM-Verschlüsselung rumgespielt, ist aber
nichts Brauchbares bei rausgekommen.

Die Animes waren übrigens "To Love Ru: Darkness" und "Usagi Drop". Hab's
dann später noch mit "Yu-Gi-Oh!" probiert. (Alle ohne DRM)

Ich glaube übrigens nicht, dass ich es diesmal hinkriege, DRM-Support
hinzuzufügen, aber man kann es ja mal probieren.


Peter Stein <notifications@github.com> schrieb am Mi., 29. Apr. 2020, 09:20:

**Comment by ptrstn** [comment]
Nice, vielleicht sind wir uns schon zufällig begegnet :-)

Dann werde ich wohl auf Screen Capture zurückgreifen müssen, aber großen Respekt für deine Arbeit! Einen Versuch war es allemal wert.

**Comment by Philippus229** [comment]
Ich finde jetzt eigentlich nicht, dass der Downloader so toll ist, aber
danke!
Hab mir die DRM-Verschlüsselung auch nochmal genauer angeschaut, aber es
scheint nicht, als könne man da was machen.

Am Mi., 29. Apr. 2020 um 14:39 Uhr schrieb Peter Stein <
notifications@github.com>:
